/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IGigEarth, IGigEarthInterface } from "../IGigEarth";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_relationshipID",
        type: "uint256",
      },
    ],
    name: "getRelationshipData",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "valuePtr",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "escrow",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "marketPtr",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "employer",
            type: "address",
          },
          {
            internalType: "address",
            name: "worker",
            type: "address",
          },
          {
            internalType: "string",
            name: "taskMetadataPtr",
            type: "string",
          },
          {
            internalType: "enum RelationshipLibrary.ContractStatus",
            name: "contractStatus",
            type: "uint8",
          },
          {
            internalType: "enum RelationshipLibrary.ContractOwnership",
            name: "contractOwnership",
            type: "uint8",
          },
          {
            internalType: "enum RelationshipLibrary.ContractPayoutType",
            name: "contractPayoutType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "wad",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "acceptanceTimestamp",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "resolutionTimestamp",
            type: "uint256",
          },
        ],
        internalType: "struct RelationshipLibrary.Relationship",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IGigEarth__factory {
  static readonly abi = _abi;
  static createInterface(): IGigEarthInterface {
    return new utils.Interface(_abi) as IGigEarthInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGigEarth {
    return new Contract(address, _abi, signerOrProvider) as IGigEarth;
  }
}
