/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITokenVault, ITokenVaultInterface } from "../ITokenVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "serviceToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "maxEntries",
        type: "uint256",
      },
    ],
    name: "getLockedEntries",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "lockedUntil",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lockedAmount",
            type: "uint256",
          },
        ],
        internalType: "struct LockedEntry[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "serviceToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "lock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "serviceToken",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "untils",
        type: "uint256[]",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITokenVault__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenVaultInterface {
    return new utils.Interface(_abi) as ITokenVaultInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenVault {
    return new Contract(address, _abi, signerOrProvider) as ITokenVault;
  }
}
