/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ITokenNameVerifier,
  ITokenNameVerifierInterface,
} from "../ITokenNameVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
    ],
    name: "verifyTokenName",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class ITokenNameVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenNameVerifierInterface {
    return new utils.Interface(_abi) as ITokenNameVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenNameVerifier {
    return new Contract(address, _abi, signerOrProvider) as ITokenNameVerifier;
  }
}
