/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IArbitrableInterface extends utils.Interface {
  functions: {
    "rule(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "rule",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "rule", data: BytesLike): Result;

  events: {
    "Ruling(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Ruling"): EventFragment;
}

export type RulingEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { _arbitrator: string; _disputeID: BigNumber; _ruling: BigNumber }
>;

export type RulingEventFilter = TypedEventFilter<RulingEvent>;

export interface IArbitrable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IArbitrableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    rule(
      _disputeID: BigNumberish,
      _ruling: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  rule(
    _disputeID: BigNumberish,
    _ruling: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    rule(
      _disputeID: BigNumberish,
      _ruling: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Ruling(address,uint256,uint256)"(
      _arbitrator?: string | null,
      _disputeID?: BigNumberish | null,
      _ruling?: null
    ): RulingEventFilter;
    Ruling(
      _arbitrator?: string | null,
      _disputeID?: BigNumberish | null,
      _ruling?: null
    ): RulingEventFilter;
  };

  estimateGas: {
    rule(
      _disputeID: BigNumberish,
      _ruling: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    rule(
      _disputeID: BigNumberish,
      _ruling: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
